### ISSUE TITLE
create cookie once css really has loaded

### ISSUE THREAD

**Issue by rauberdaniel** [FilipBartos/express-handlebars-criticalcss#1]
I know it’s an edge case but shouldn’t `createCookie` (https://github.com/FilipBartos/express-handlebars-criticalcss/blob/master/views/partials/fastjs.handlebars#L8) actually be called inside the `handleFastcss` function as it should only create the cookie once the css actually has loaded? This might prevent issues when the site is opened and closed again before the css has loaded (but the cookie was set already).

I assume that browsers will cancel the CSS download once the site is closed. If that is not the case it doesn’t matter.

**Comment by FilipBartos** [comment]
Nice catch Daniel, you are right :) Thanks for your comment. It's better to call `createCookie` inside the `handleFastcss` function.

I have updated article and `fastjs.handlebars` file.
